### PR TITLE
Adjust Message to be compatible with PHP 8.1

### PR DESCRIPTION
**Pull request by pklink**
Relating to https://github.com/contentful/contentful.php/issues/311

Sorry, I've seen to late, that this problem is located in the `contentful-core` repository

### CODE REVIEW

**Comment by pklink** [comment]
Sorry, I don't understand [this](https://app.circleci.com/pipelines/github/contentful/contentful-core.php/63/workflows/01b8b13f-bb34-44cc-9f19-063e634f35fd/jobs/688) problem. Is it really code-related?

**Comment by Sebb767** [comment]
Hi @pklink ,

first, thanks a lot for pointing out the issue and directly contributing the fix! I'll include it in the next release.

The problem you saw in the CI is not code related, that's a backwards compatibility break in on of our dependencies; unfortunately, this warning will continue until our next major release. Sorry for the trouble, I should probably add a warning in the README.

**Comment by BrentRobert** [comment]
Hi @Sebb767 when can this fix be released?

**Comment by Sebb767** [comment]
Hi @BrentRobert ,

I'll create a release today or tomorrow! :) Sorry, totally missed that I didn't release this change yet

**Comment by BrentRobert** [comment]
@Sebb767 Thanks, no worries, was just wondering as we get these as deprecation warnings on our environments :)

**Comment by BrentRobert** [comment]
@Sebb767 poking you again, let me know if I can do anything to assist :)

**Comment by pkid169** [comment]
Hi @Sebb767, I'm just pulling the latest (v 6.4.0) and still encountering this issue. Did you ever manage to release the above?

**Comment by Sebb767** [comment]
Hey @pkid169 @BrentRobert , this is now released with [v7.0.0](https://github.com/contentful/contentful.php/releases/tag/v7.0.0) :)

**Pull request merged**
