### PR TITLE
Allow guzzlehttp/psr7 2.x

### PR DESCRIPTION
**Pull request by philipnewcomer**
I have a third party package that requires  guzzlehttp/psr7 2.x. However, contentful/core requires guzzlehttp/psr7 1.x, so I can't have both Contentful and the third party package installed at the same time.

This PR updates contentful/core to work with either psr7 1.x or 2.x by updating usages of the psr7 helpers which were removed in psr7 2.0.

### CODE REVIEW

**Comment by i-bajrai** [comment]
`"guzzlehttp/psr7": "^1.5|^1.6|^2.0",`

is code in this pr backwards compatible with 1.5 and 1.6? If not it should just be ^2.0

**Comment by ghost** [comment]
+1. Laravel 8 and up have a dependency on this version of PSR7 as well.

**Review by Sebb767 — APPROVED** [review]
Thanks for contributing! I'll release these changes soon.

**Comment by i-bajrai** [comment]
@Sebb767 I think if someone with 1.6 brings this in their code will break:

https://github.com/guzzle/psr7/blob/1.6.1/src/functions.php

**Comment by Sebb767** [comment]
@i-bajrai If I read the changelog correctly, this will only break code if it uses functions deprecated in 1.6 or a PHP version which is no longer supported by Contentful anyway: https://github.com/guzzle/psr7/blob/master/CHANGELOG.md#200beta-1---2021-03-21

That being said, we need to go to psr7 v2 anyway since Laravel and some other packages depend on it. The only question is whether this needs to be a major release (as of now, I think not and `^1.6|^2.0` should work).

**Comment by i-bajrai** [comment]
All good! I think if you set it to 2.0 then it will stop people from automatically being able to upgrade to a version that will break their code, flagging them to update psr7 to the correct version.

Ie if they currently have a code base with 1.6 and they upgrade contentful, this pr will contain code ~no longer~ that does not exist in 1.6 😄

**Pull request merged**
